from sqlalchemy import text


async def ensure_runtime_database(conn):
    await conn.execute(text("SELECT pg_advisory_xact_lock(2026060201)"))
    await ensure_runtime_schema(conn)
    await ensure_runtime_indexes(conn)


async def ensure_runtime_schema(conn):
    statements = [
        # api_keys was added after early deployments; create_all does not alter old tables.
        "ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS name varchar(128)",
        "ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS key_hash varchar(256)",
        "ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS key_prefix varchar(8)",
        "ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS permissions varchar[]",
        "ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true",
        "ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS last_used_at timestamptz",
        "ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS created_by integer",
        "ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS expires_at timestamptz",
        "ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now()",
        "ALTER TABLE api_keys ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now()",
        "UPDATE api_keys SET is_active = true WHERE is_active IS NULL",
        "UPDATE api_keys SET permissions = ARRAY['push:read','push:callback']::varchar[] WHERE permissions IS NULL",
        "UPDATE api_keys SET created_at = now() WHERE created_at IS NULL",
        "UPDATE api_keys SET updated_at = now() WHERE updated_at IS NULL",
        # admin users and audit logs.
        "ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS username varchar(64)",
        "ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS password_hash varchar(256)",
        "ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true",
        "ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS last_login_at timestamptz",
        "ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now()",
        "ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now()",
        "UPDATE admin_users SET is_active = true WHERE is_active IS NULL",
        "UPDATE admin_users SET created_at = now() WHERE created_at IS NULL",
        "UPDATE admin_users SET updated_at = now() WHERE updated_at IS NULL",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS user_id integer",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS action varchar(64)",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS target_type varchar(64)",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS target_id integer",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS details jsonb",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS ip_address varchar(45)",
        "ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now()",
        "UPDATE audit_logs SET created_at = now() WHERE created_at IS NULL",
        # telegram push records.
        "ALTER TABLE telegram_push_records ADD COLUMN IF NOT EXISTS resource_id integer",
        "ALTER TABLE telegram_push_records ADD COLUMN IF NOT EXISTS status varchar(32) DEFAULT 'pending'",
        "ALTER TABLE telegram_push_records ADD COLUMN IF NOT EXISTS push_payload jsonb",
        "ALTER TABLE telegram_push_records ADD COLUMN IF NOT EXISTS response_payload jsonb",
        "ALTER TABLE telegram_push_records ADD COLUMN IF NOT EXISTS attempt integer DEFAULT 0",
        "ALTER TABLE telegram_push_records ADD COLUMN IF NOT EXISTS error_message text",
        "ALTER TABLE telegram_push_records ADD COLUMN IF NOT EXISTS pushed_at timestamptz",
        "ALTER TABLE telegram_push_records ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now()",
        "ALTER TABLE telegram_push_records ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now()",
        "UPDATE telegram_push_records SET status = 'pending' WHERE status IS NULL",
        "UPDATE telegram_push_records SET attempt = 0 WHERE attempt IS NULL",
        "UPDATE telegram_push_records SET created_at = now() WHERE created_at IS NULL",
        "UPDATE telegram_push_records SET updated_at = now() WHERE updated_at IS NULL",
        # resources evolved during the workflow hardening.
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS batch_id integer",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS name varchar(512)",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS name_normalized varchar(512)",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS tags varchar(512)",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS tags_array varchar[]",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS original_link text",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS share_id varchar(128)",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS extract_code varchar(64)",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS status varchar(32) DEFAULT U&'\\5F85\\8F6C\\5B58'",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS transfer_account_id integer",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS transferred_file_id text",
        "ALTER TABLE resources ALTER COLUMN transferred_file_id TYPE text",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS new_share_id varchar(128)",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS new_extract_code varchar(64)",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS new_share_link text",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS error_message text",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS error_response jsonb",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS retry_count integer DEFAULT 0",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS max_retries integer DEFAULT 3",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS duplicate_of_id integer",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS transferred_at timestamptz",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS pushed_at timestamptz",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now()",
        "ALTER TABLE resources ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now()",
        "UPDATE resources SET status = U&'\\5F85\\8F6C\\5B58' WHERE status IS NULL",
        "UPDATE resources SET retry_count = 0 WHERE retry_count IS NULL",
        "UPDATE resources SET max_retries = 3 WHERE max_retries IS NULL",
        "UPDATE resources SET created_at = now() WHERE created_at IS NULL",
        "UPDATE resources SET updated_at = now() WHERE updated_at IS NULL",
        # tasks.
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS resource_id integer",
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS task_type varchar(32) DEFAULT 'transfer'",
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS status varchar(32) DEFAULT 'pending'",
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS account_id integer",
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS attempt integer DEFAULT 0",
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS max_attempts integer DEFAULT 3",
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS error_message text",
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS error_response jsonb",
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS checkpoint jsonb",
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS started_at timestamptz",
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS completed_at timestamptz",
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS next_retry_at timestamptz",
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now()",
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now()",
        "UPDATE tasks SET task_type = 'transfer' WHERE task_type IS NULL",
        "UPDATE tasks SET status = 'pending' WHERE status IS NULL",
        "UPDATE tasks SET attempt = 0 WHERE attempt IS NULL",
        "UPDATE tasks SET max_attempts = 3 WHERE max_attempts IS NULL",
        "UPDATE tasks SET created_at = now() WHERE created_at IS NULL",
        "UPDATE tasks SET updated_at = now() WHERE updated_at IS NULL",
        # duplicate reviews.
        "ALTER TABLE duplicate_reviews ADD COLUMN IF NOT EXISTS new_resource_id integer",
        "ALTER TABLE duplicate_reviews ADD COLUMN IF NOT EXISTS existing_resource_id integer",
        "ALTER TABLE duplicate_reviews ADD COLUMN IF NOT EXISTS similarity_score double precision DEFAULT 0",
        "ALTER TABLE duplicate_reviews ADD COLUMN IF NOT EXISTS match_reason varchar(256)",
        "ALTER TABLE duplicate_reviews ADD COLUMN IF NOT EXISTS decision varchar(32) DEFAULT 'pending'",
        "ALTER TABLE duplicate_reviews ADD COLUMN IF NOT EXISTS decided_by integer",
        "ALTER TABLE duplicate_reviews ADD COLUMN IF NOT EXISTS decided_at timestamptz",
        "ALTER TABLE duplicate_reviews ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now()",
        "ALTER TABLE duplicate_reviews ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now()",
        "UPDATE duplicate_reviews SET similarity_score = 0 WHERE similarity_score IS NULL",
        "UPDATE duplicate_reviews SET decision = 'pending' WHERE decision IS NULL",
        "UPDATE duplicate_reviews SET created_at = now() WHERE created_at IS NULL",
        "UPDATE duplicate_reviews SET updated_at = now() WHERE updated_at IS NULL",
        # import batches.
        "ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS filename varchar(256)",
        "ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS stored_path text",
        "ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS total_rows integer DEFAULT 0",
        "ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS processed_rows integer DEFAULT 0",
        "ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS valid_rows integer DEFAULT 0",
        "ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS new_count integer DEFAULT 0",
        "ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS duplicate_skipped integer DEFAULT 0",
        "ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS fuzzy_flagged integer DEFAULT 0",
        "ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS parse_failed integer DEFAULT 0",
        "ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS status varchar(32) DEFAULT 'pending'",
        "ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS error_message text",
        "ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS imported_by integer",
        "ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS completed_at timestamptz",
        "ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now()",
        "ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now()",
        "UPDATE import_batches SET total_rows = 0 WHERE total_rows IS NULL",
        "UPDATE import_batches SET processed_rows = 0 WHERE processed_rows IS NULL",
        "UPDATE import_batches SET valid_rows = 0 WHERE valid_rows IS NULL",
        "UPDATE import_batches SET new_count = 0 WHERE new_count IS NULL",
        "UPDATE import_batches SET duplicate_skipped = 0 WHERE duplicate_skipped IS NULL",
        "UPDATE import_batches SET fuzzy_flagged = 0 WHERE fuzzy_flagged IS NULL",
        "UPDATE import_batches SET parse_failed = 0 WHERE parse_failed IS NULL",
        "UPDATE import_batches SET status = 'pending' WHERE status IS NULL",
        "UPDATE import_batches SET created_at = now() WHERE created_at IS NULL",
        "UPDATE import_batches SET updated_at = now() WHERE updated_at IS NULL",
        # raw import rows.
        "ALTER TABLE raw_import_rows ADD COLUMN IF NOT EXISTS batch_id integer",
        "ALTER TABLE raw_import_rows ADD COLUMN IF NOT EXISTS row_number integer",
        "ALTER TABLE raw_import_rows ADD COLUMN IF NOT EXISTS raw_data jsonb",
        "ALTER TABLE raw_import_rows ADD COLUMN IF NOT EXISTS row_hash varchar(64)",
        "ALTER TABLE raw_import_rows ADD COLUMN IF NOT EXISTS status varchar(32) DEFAULT 'pending'",
        "ALTER TABLE raw_import_rows ADD COLUMN IF NOT EXISTS resource_id integer",
        "ALTER TABLE raw_import_rows ADD COLUMN IF NOT EXISTS error_message text",
        "ALTER TABLE raw_import_rows ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now()",
        "ALTER TABLE raw_import_rows ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now()",
        "UPDATE raw_import_rows SET status = 'pending' WHERE status IS NULL",
        "UPDATE raw_import_rows SET created_at = now() WHERE created_at IS NULL",
        "UPDATE raw_import_rows SET updated_at = now() WHERE updated_at IS NULL",
        # accounts.
        "ALTER TABLE guangya_accounts ADD COLUMN IF NOT EXISTS name varchar(128)",
        "ALTER TABLE guangya_accounts ADD COLUMN IF NOT EXISTS device_id varchar(128)",
        "ALTER TABLE guangya_accounts ADD COLUMN IF NOT EXISTS access_token text",
        "ALTER TABLE guangya_accounts ADD COLUMN IF NOT EXISTS refresh_token text",
        "ALTER TABLE guangya_accounts ADD COLUMN IF NOT EXISTS token_expires_at timestamptz",
        "ALTER TABLE guangya_accounts ADD COLUMN IF NOT EXISTS status varchar(32) DEFAULT 'available'",
        "ALTER TABLE guangya_accounts ADD COLUMN IF NOT EXISTS total_capacity_bytes bigint",
        "ALTER TABLE guangya_accounts ADD COLUMN IF NOT EXISTS used_capacity_bytes bigint",
        "ALTER TABLE guangya_accounts ADD COLUMN IF NOT EXISTS default_parent_id varchar(64) DEFAULT ''",
        "ALTER TABLE guangya_accounts ADD COLUMN IF NOT EXISTS priority integer DEFAULT 0",
        "ALTER TABLE guangya_accounts ADD COLUMN IF NOT EXISTS last_used_at timestamptz",
        "ALTER TABLE guangya_accounts ADD COLUMN IF NOT EXISTS rate_limited_until timestamptz",
        "ALTER TABLE guangya_accounts ADD COLUMN IF NOT EXISTS error_count integer DEFAULT 0",
        "ALTER TABLE guangya_accounts ADD COLUMN IF NOT EXISTS last_error text",
        "ALTER TABLE guangya_accounts ADD COLUMN IF NOT EXISTS processed_count integer DEFAULT 0",
        "ALTER TABLE guangya_accounts ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now()",
        "ALTER TABLE guangya_accounts ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now()",
        "UPDATE guangya_accounts SET status = 'available' WHERE status IS NULL",
        "UPDATE guangya_accounts SET default_parent_id = '' WHERE default_parent_id IS NULL",
        "UPDATE guangya_accounts SET priority = 0 WHERE priority IS NULL",
        "UPDATE guangya_accounts SET error_count = 0 WHERE error_count IS NULL",
        "UPDATE guangya_accounts SET processed_count = 0 WHERE processed_count IS NULL",
        "UPDATE guangya_accounts SET created_at = now() WHERE created_at IS NULL",
        "UPDATE guangya_accounts SET updated_at = now() WHERE updated_at IS NULL",
        # runtime controls.
        "CREATE TABLE IF NOT EXISTS system_controls (key varchar(64) PRIMARY KEY, value jsonb NOT NULL DEFAULT '{}'::jsonb, updated_at timestamptz DEFAULT now())",
        "INSERT INTO system_controls (key, value) VALUES ('worker_control', '{\"paused\": false}'::jsonb) ON CONFLICT (key) DO NOTHING",
    ]
    for statement in statements:
        await conn.execute(text(statement))


async def ensure_runtime_indexes(conn):
    statements = [
        "CREATE EXTENSION IF NOT EXISTS pg_trgm",
        "CREATE INDEX IF NOT EXISTS idx_api_keys_hash ON api_keys (key_hash)",
        "CREATE INDEX IF NOT EXISTS idx_resources_status_created_at ON resources (status, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_resources_transferred_at ON resources (transferred_at)",
        "CREATE INDEX IF NOT EXISTS idx_tasks_status_created_at ON tasks (status, created_at)",
        "CREATE INDEX IF NOT EXISTS idx_push_records_resource_status ON telegram_push_records (resource_id, status)",
        "CREATE INDEX IF NOT EXISTS idx_raw_import_rows_batch_status ON raw_import_rows (batch_id, status, row_number)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_raw_import_rows_batch_row_number ON raw_import_rows (batch_id, row_number)",
        "CREATE INDEX IF NOT EXISTS idx_raw_import_rows_hash ON raw_import_rows (row_hash)",
        "CREATE INDEX IF NOT EXISTS idx_resources_share_extract ON resources (share_id, extract_code)",
        "CREATE INDEX IF NOT EXISTS idx_resources_name_trgm ON resources USING gin (name gin_trgm_ops)",
        "CREATE INDEX IF NOT EXISTS idx_resources_tags_trgm ON resources USING gin (tags gin_trgm_ops)",
        "CREATE INDEX IF NOT EXISTS idx_resources_original_link_trgm ON resources USING gin (original_link gin_trgm_ops)",
        "CREATE INDEX IF NOT EXISTS idx_resources_new_share_link_trgm ON resources USING gin (new_share_link gin_trgm_ops)",
    ]
    for statement in statements:
        await conn.execute(text(statement))
